export * from "./getUserById"
export * from "./getClassesByTeacherId"
export * from "./getClassById"
export * from "./getCourseById"
export * from "./getCoursesByClassId"
export * from "./getNews"
export * from "./getNewsByTeacherId"
export * from "./getPieceOfNewsById"