// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model
//
//type Class struct {
//	ID        string `json:"id"`
//	Number    int    `json:"number"`
//	Letter    string `json:"letter"`
//	TeacherID string `json:"teacher_id"`
//}
//
//type Course struct {
//	ID          string  `json:"_id"`
//	Title       string  `json:"title"`
//	Description *string `json:"description,omitempty"`
//	ClassID     string  `json:"class_id"`
//}
//
//type CreateCourseInput struct {
//	Title       string  `json:"title"`
//	Description *string `json:"description,omitempty"`
//}
//
//type CreateTaskInput struct {
//	Title       string  `json:"title"`
//	Description *string `json:"description,omitempty"`
//	Deadline    *string `json:"deadline,omitempty"`
//}
//
//type Student struct {
//	ID      string `json:"id"`
//	ClassID string `json:"class_id"`
//}
//
//type Task struct {
//	ID          string  `json:"_id"`
//	Title       string  `json:"title"`
//	Description *string `json:"description,omitempty"`
//	Deadline    *string `json:"deadline,omitempty"`
//	CourseID    string  `json:"course_id"`
//}
//
//type Teacher struct {
//	ID string `json:"id"`
//}
//
//type UpdateCourseInput struct {
//	ID          string  `json:"_id"`
//	Title       string  `json:"title"`
//	Description *string `json:"description,omitempty"`
//}
//
//type UpdateTaskInput struct {
//	ID          string  `json:"_id"`
//	Title       string  `json:"title"`
//	Description *string `json:"description,omitempty"`
//	Deadline    *string `json:"deadline,omitempty"`
//}
//
//type User struct {
//	ID               string  `json:"id"`
//	Role             string  `json:"role"`
//	Email            string  `json:"email"`
//	Name             string  `json:"name"`
//	Surname          string  `json:"surname"`
//	Password         string  `json:"password"`
//	Image            *string `json:"image,omitempty"`
//	RegistrationDate string  `json:"registration_date"`
//	BirthdayDate     *string `json:"birthday_date,omitempty"`
//}
